### ISSUE TITLE
Error en código

### ISSUE THREAD

**Issue by Cristopher-08** [bridneysl5/trivianew#1]
## Error encontrado
A la hora de jugar la trivia no entra a la categoría Ciencia

![image](https://user-images.githubusercontent.com/37849703/190918487-82bba393-8269-44aa-a10b-2102deaa92eb.png)

## Recomedación
Podrías ver el formato de tu csv y como lo esta llamando en esa categoría

`def crear_lista_preguntas(questions):
    """Función para ordenar preguntas en una lista"""
    lista_preguntas = []
    for q in questions:
        nueva_pregunta = Question(q["PREGUNTAS"], q["RESPUESTAS"], q["CATEGORIA"])
        lista_preguntas.append(nueva_pregunta)
    return lista_preguntas`

**Comment by bridneysl5** [comment]
Se cambio las categorías a una sola

**Comment by bridneysl5** [comment]
Ya se soluciono el bug
