### ISSUE TITLE
Recomendación 01

### ISSUE THREAD

**Issue by Cristopher-08** [bridneysl5/trivianew#2]
## Colores
Colocar lineas de codigo para que no se vea tan monócormo tu trivial

![image](https://user-images.githubusercontent.com/37849703/190928452-eb157a52-ff03-41d5-93fe-945f6a81149d.png)

## Recomendación
Usar
RED = '\033[31m'
GREEN = '\033[32m'
YELLOW = '\033[33m'
BLUE = '\033[34m'
MAGENTA = '\033[35m'
CYAN = '\033[36m'
WHITE = '\033[37m'
RESET = '\033[39m'

![image](https://user-images.githubusercontent.com/37849703/190928473-0d3ef1f3-a2bb-4f15-868f-c5f12ebf47b1.png)

*Codigo:
`def theme():
    print(GREEN+"""
   ._________________.
   |.---------------.|
   ||     STAR      ||
   ||   -._ .-.     ||
   ||   -._| | |    ||
   ||   -._|"|"|    ||
   ||   -._|.-.|    ||
   ||_______________||
   /.-.-.-.-.-.-.-.-.\
  /.-.-.-.-.-.-.-.-.-.\
 /.-.-.-.-.-.-.-.-.-.-.\
/______/__________\___o_\ 
\_______________________/
"""+RESET)`

**Comment by bridneysl5** [comment]
Se cambio de color y de diseño
