### ISSUE TITLE
Recomendación 02

### ISSUE THREAD

**Issue by Cristopher-08** [bridneysl5/trivianew#3]
Colocar instrucciones de juego para tu trivia y ser mas amigable si se usa la trivia en dispositivo móvil, se complica para responder
![image](https://user-images.githubusercontent.com/37849703/190928685-be23f1c9-a15e-4700-adf9-2e1bab831104.png)

Recomendación 03
El tiempo de espera de respuesta es muy rápido, usar `.sleep(8)` , para que pueda ser mas interactivo con el usuario

**Comment by bridneysl5** [comment]
Ya se extendió el tiempo al usuario
